name = "cardano/multisig"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'cardano/multisig'"

[repository]
user = "cardano"
project = "multisig"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
